version: '2'
services:
  nginx:
    image: "nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../etc/nginx:/etc/nginx
      - ../etc/localtime:/etc/localtime
      - ../app/web:/app/web
    links:
      - php7-fpm:php-fpm
    depends_on:
      - php7-fpm
  php7-fpm:
    image: "zterry95/docker-php7:latest"
    volumes:
      - ../app/web:/app/web
      - ../etc/localtime:/etc/localtime
      - ../etc/php:/usr/local/etc/php
      - ../etc/php-fpm:/usr/local/etc
    depends_on:
      - mysql
    links:
      - mysql:mysql
  mysql:
    image: mysql/mysql-server:5.7.17
    ports:
      - "3306:3306"
    volumes:
      - ../etc/localtime:/etc/localtime
      - ./mysql-data:/var/lib/mysql
      #- ./etc/mysql:/etc/mysql/conf.d
      - ../etc/mysql/my.cnf:/etc/my.cnf
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
