version: '2'
services:
  nginx:
    image: "ahaschool/nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../app/web:/app/web
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./etc/localtime:/etc/localtime
    network_mode: "bridge"
    links:
      - php-xdebug:php-xdebug
    depends_on:
      - php-xdebug
  php-xdebug:
    image: "ahaschool/php-xdebug:latest"
    volumes:
      - ../app/web:/app/web
      - ./etc/localtime:/etc/localtime
      - ./etc/php-fpm:/usr/local/etc
    network_mode: "bridge"
    depends_on:
      - redis
      - mysql
    links:
      - redis:localredis
      - mysql:localmysql
  redis:
    image: "ahaschool/redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./etc/php-fpm:/usr/local/etc
      - ./etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
    network_mode: "bridge"
    command: "redis-server /usr/local/etc/redis/redis.conf"
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - ../data/mysql-data:/var/lib/mysql
      - ./etc/localtime:/etc/localtime
      - ./etc/mysql/my.cnf:/etc/my.cnf
    network_mode: "bridge"
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
